apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadakcf4423-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadakcf4423-tenant-component
    app.kubernetes.io/part-of: loadakcf4423-tenant-app
  name: loadakcf4423-tenant-component
  namespace: loadakcf4423-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadakcf4423-tenant-component
    weight: null
status: {}
